# Generated by Django 3.2.25 on 2025-05-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
