# Generated by Django 3.2.25 on 2025-05-03 05:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('sherlock', django.db.models.manager.Manager()),
            ],
        ),
    ]
