# Generated by Django 3.2.25 on 2025-05-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_userinfo_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
    ]
